default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode

development:
  <<: *default
  database: development
  username: root
  password:


test:
  <<: *default
  database: test
  username: root
  password:

# HEROKU
production:
  <<: *default